# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: eventgrid.azure.upbound.io/v1beta1
kind: SystemTopicEventSubscription
metadata:
  annotations:
    meta.upbound.io/example-id: eventgrid/v1beta1/systemtopiceventsubscription
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-event-subscription
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: systemtopic-sub
    storageQueueEndpoint:
      queueNameSelector:
        matchLabels:
          testing.upbound.io/example-name: systemtopic-sub
      storageAccountIdSelector:
        matchLabels:
          testing.upbound.io/example-name: systemtopic-sub
    systemTopicSelector:
      matchLabels:
        testing.upbound.io/example-name: systemtopic-sub

---

apiVersion: eventgrid.azure.upbound.io/v1beta1
kind: SystemTopic
metadata:
  annotations:
    meta.upbound.io/example-id: eventgrid/v1beta1/systemtopiceventsubscription
  labels:
    testing.upbound.io/example-name: systemtopic-sub
  name: systemtopic-sub
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: systemtopic-sub
    sourceArmResourceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: systemtopic-sub
    topicType: Microsoft.Storage.StorageAccounts

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: eventgrid/v1beta1/systemtopiceventsubscription
  labels:
    testing.upbound.io/example-name: systemtopic-sub
  name: systemtopic-sub
spec:
  forProvider:
    location: West Europe

---

apiVersion: storage.azure.upbound.io/v1beta2
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: eventgrid/v1beta1/systemtopiceventsubscription
  labels:
    testing.upbound.io/example-name: systemtopic-sub
  name: example5643045814
spec:
  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: systemtopic-sub
    tags:
      environment: staging

---

apiVersion: storage.azure.upbound.io/v1beta1
kind: Queue
metadata:
  annotations:
    meta.upbound.io/example-id: eventgrid/v1beta1/systemtopiceventsubscription
  labels:
    testing.upbound.io/example-name: systemtopic-sub
  name: example
spec:
  forProvider:
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: systemtopic-sub
